# Generated by Django 5.0.1 on 2025-12-28 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('confirmed', 'Підтверджено'), ('processing', 'Обробляється'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума товарів')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вартість доставки')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Податок')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('payment_method', models.CharField(choices=[('card', 'Картка'), ('cash', 'Готівка'), ('online', 'Онлайн')], max_length=20, verbose_name='Спосіб оплати')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплати')),
                ('delivery_method', models.CharField(choices=[('nova_poshta', 'Нова Пошта'), ('ukr_poshta', 'Укрпошта'), ('courier', "Кур'єр"), ('pickup', 'Самовивіз')], max_length=20, verbose_name='Спосіб доставки')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Індекс')),
                ('country', models.CharField(default='Україна', max_length=100, verbose_name='Країна')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('tracking_number', models.CharField(blank=True, max_length=200, verbose_name='Номер відстеження')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Назва товару')),
                ('product_sku', models.CharField(max_length=100, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Товар замовлення',
                'verbose_name_plural': 'Товари замовлення',
            },
        ),
    ]
