# Generated by Django 5.0.1 on 2025-12-28 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Підзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Зображення')),
                ('link', models.URLField(blank=True, verbose_name='Посилання')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Банер',
                'verbose_name_plural': 'Банери',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Контент')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Витяг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Зображення')),
                ('views_count', models.IntegerField(default=0, verbose_name='Кількість переглядів')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пост блогу',
                'verbose_name_plural': 'Пости блогу',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Зображення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткий опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('discount_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка %')),
                ('variety', models.CharField(blank=True, choices=[('early', 'Ранній'), ('mid', 'Середній'), ('late', 'Пізній'), ('mid-late', 'Середньо-пізній')], max_length=50, verbose_name='Сорт')),
                ('age', models.CharField(blank=True, max_length=100, verbose_name='Вік саджанця')),
                ('fruit_weight', models.CharField(blank=True, max_length=100, verbose_name='Маса плоду')),
                ('ripening_time', models.CharField(blank=True, max_length=200, verbose_name='Термін дозрівання')),
                ('planting_season', models.CharField(blank=True, choices=[('spring', 'Весна'), ('summer', 'Літо'), ('autumn', 'Осінь'), ('winter', 'Зима')], max_length=50, verbose_name='Сезон посадки')),
                ('package_type', models.CharField(blank=True, help_text='Наприклад: відкритий корінь, в горщику 10л', max_length=100, verbose_name='Тип упаковки')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Залишок')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул (Код товару)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вага (кг)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Бестселер')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новинка')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярний')),
                ('is_in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акція')),
                ('delivery_info', models.CharField(blank=True, help_text='Наприклад: НА ВЕСНУ 2026', max_length=200, verbose_name='Інформація про доставку')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Зображення')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Головне зображення')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('comment', models.TextField(verbose_name='Коментар')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Підтверджена покупка')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Схвалено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Список бажань',
                'verbose_name_plural': 'Списки бажань',
            },
        ),
    ]
