# Generated by Django 5.0.1 on 2026-03-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Артикул (Код товару)'),
        ),
    ]
