# Generated by Django 5.0.1 on 2026-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_footersection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersection',
            name='description',
            field=models.TextField(blank=True, help_text="Необов'язковий текст, що відображається під заголовком розділу", verbose_name='Текст під заголовком'),
        ),
    ]
