# Generated by Django 5.0.1 on 2026-04-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_footersection_description'),
        ('content', '0004_footerlink_description'),
    ]

    operations = [
    ]
