# Generated by Django 5.0.1 on 2026-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_footersociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='description',
            field=models.TextField(blank=True, help_text="Необов'язковий пояснювальний текст під посиланням", verbose_name='Опис'),
        ),
    ]
