# Generated by Django 5.0.1 on 2026-04-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_footerlink_description'),
        ('content', '0007_footersociallink_settings_fk'),
    ]

    operations = [
    ]
