# Generated by Django 5.0.1 on 2026-04-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_aboutcontent_contactcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcontent',
            name='hours_weekday',
            field=models.CharField(default='8:00–18:00', max_length=50, verbose_name='Буднях — години'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='hours_weekday_label',
            field=models.CharField(default='ПН–ПТ', max_length=50, verbose_name='Буднях — підпис'),
        ),
    ]
