# Generated by Django 5.0.1 on 2026-04-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_contactcontent_hours_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Надсилати email-сповіщення')),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP-сервер')),
                ('email_port', models.PositiveSmallIntegerField(default=587, verbose_name='SMTP-порт')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Використовувати TLS')),
                ('email_host_user', models.CharField(blank=True, max_length=200, verbose_name='Логін (email відправника)')),
                ('email_host_password', models.CharField(blank=True, help_text='Для Gmail використовуйте App Password (не основний пароль акаунту)', max_length=500, verbose_name='Пароль / App Password')),
                ('admin_notification_email', models.EmailField(blank=True, help_text='На цю адресу надходитимуть сповіщення про нові замовлення', max_length=254, verbose_name='Email адміністратора')),
                ('viber_enabled', models.BooleanField(default=False, verbose_name='Надсилати Viber-сповіщення')),
                ('viber_bot_token', models.CharField(blank=True, help_text='Отримайте токен на developers.viber.com → My bots → Bot info → Token', max_length=500, verbose_name='Viber Bot Token')),
                ('viber_admin_receiver', models.CharField(blank=True, help_text='Напишіть боту з вашого Viber — отримаєте ID у webhook-події sender.id', max_length=200, verbose_name='Viber User ID адміністратора')),
            ],
            options={
                'verbose_name': 'Налаштування сповіщень',
                'verbose_name_plural': 'Налаштування сповіщень',
            },
        ),
    ]
