# Generated by Django 5.0.1 on 2026-04-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(help_text="Внутрішній шлях: /about або зовнішній: https://... (заповнюється автоматично якщо прив'язана сторінка)", max_length=500, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=models.TextField(help_text='Підтримується HTML-розмітка. Наприклад: &lt;h2&gt;Заголовок&lt;/h2&gt;&lt;p&gt;Текст&lt;/p&gt;', verbose_name='Вміст сторінки'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='footer_link',
            field=models.OneToOneField(blank=True, help_text='Якщо вказано — URL посилання буде автоматично встановлено на /pages/<slug>', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page', to='content.footerlink', verbose_name='Посилання футера'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='slug',
            field=models.SlugField(help_text='Заповнюється автоматично. Сторінка буде доступна за адресою /pages/&lt;slug&gt;', max_length=255, unique=True, verbose_name='URL-ключ (slug)'),
        ),
    ]
