# Generated by Django 5.0.1 on 2025-12-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('completed', 'Завершено'), ('failed', 'Помилка'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Метод оплати')),
                ('transaction_id', models.CharField(blank=True, max_length=200, verbose_name='ID транзакції')),
                ('payment_details', models.JSONField(blank=True, null=True, verbose_name='Деталі платежу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'ordering': ['-created_at'],
            },
        ),
    ]
